version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vvv}
      MYSQL_USER: ${MYSQL_USER:-vvvuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-s3cret}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER:-vvvuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-s3cret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vvv}
      REALTIME_TOKEN: ${REALTIME_TOKEN:-sometoken}
      NODE_ENV: production
    depends_on:
      - mysql

volumes:
  mysql_data: