services:
  - type: web
    name: vvv-app
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: REALTIME_TOKEN
        generateValue: true
